DROP TABLE IF EXISTS Blogs;
 
CREATE TABLE Blogs(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  Blog_Title VARCHAR(250) NOT NULL,
  Blog_Date INTEGER(250) NOT NULL,
  Blog_Content VARCHAR(250) DEFAULT NULL
);
